[project]
name = "rag-pdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "docling>=2.73.1",
    "fastembed",
    "langchain-core",
    "ollama>=0.6.1",
    "pytest>=9.0.2",
    "qdrant-client>=1.17.0",
    "datasets",
    "ranx",
    "transformers",
    "ragas",
]
